services:
  - type: web
    name: sunday-soccer-manager-live
    runtime: node
    plan: free
    buildCommand: echo "No dependencies to install"
    startCommand: node server.js
    autoDeployTrigger: commit
    envVars:
      - key: ADMIN_EMAIL
        value: admin@sundaysoccer.local
      - key: ADMIN_PASSWORD
        value: sunday-admin
